# Generated by Django 3.0.5 on 2020-05-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
