# Generated by Django 3.0.5 on 2020-05-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_auto_20200519_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='days_free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('number_student', models.IntegerField()),
                ('portion', models.IntegerField()),
                ('all_portion', models.IntegerField()),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canteen.products')),
            ],
        ),
        migrations.CreateModel(
            name='days_cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('number_student', models.IntegerField()),
                ('portion', models.IntegerField()),
                ('all_portion', models.IntegerField()),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canteen.products')),
            ],
        ),
    ]
